services:
  db:
    image: postgres:18-alpine
    container_name: ccdb
    restart: always
    shm_size: 128mb
    environment:
      # Application user and password
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      # Database service name
      POSTGRES_DB: ccdb
    volumes:
      # Persist data
      - data:/var/lib/postgresql/data
      # Database initialization scripts
      - ./seeds:/docker-entrypoint-initdb.d:Z,ro
    ports:
      - 5432:5432
volumes:
  data:
